### ISSUE TITLE
SNMPINDEX lost ?

### ISSUE THREAD

**Issue by igloo777** [v-zhuravlev/zbx_template_pack#4]
Привет! 
```
         <template>Template Module Interfaces SNMPv2</template>
         <name>Template Module Interfaces SNMPv2</name>
         <description>Template Interfaces version: 0.14
MIBs used:
IF-MIB</description>
```

SNMPINDEX пропал? или дергается из какого то другого темплейта? 

`discovery[{#IFOPERSTATUS},1.3.6.1.2.1.2.2.1.8,{#IFADMINSTATUS},1.3.6.1.2.1.2.2.1.7,{#IFALIAS},1.3.6.1.2.1.31.1.1.1.18,{#IFNAME},1.3.6.1.2.1.31.1.1.1.1,{#IFDESCR},1.3.6.1.2.1.2.2.1.2,{#IFTYPE},1.3.6.1.2.1.2.2.1.3]`

**Comment by colttt** [comment]
Hello igloo777,
the SNMPINDEX is an default one, it is still available, also if you not specify it in the discovery rule. Please take a look in the documentation: https://www.zabbix.com/documentation/3.4/manual/discovery/low_level_discovery/snmp_oids

**Comment by v-zhuravlev** [comment]
SNMPINDEX is always available, yes.
