### ISSUE TITLE
Template Cisco CISCO-PROCESS-MIB - wrong Cpu load counter?

### ISSUE THREAD

**Issue by igloo777** [v-zhuravlev/zbx_template_pack#5]
Hi guys!
In 
```
Template Cisco CISCO-PROCESS-MIB version: 0.13 (and 0.14 already)
MIBs used:
CISCO-PROCESS-MIB

```
i see that you measure CPU Load as cpmCPUTotal5minRev (avg value for 5 minutes interval) every 3 minutes.. So you get an average value of average value for period, that less than averaging period on remote device (also every 3 minutes you get a value, containing a part of averaged data of the previous period, due to the overlapping). Result value seems too over-averaged (you loose a peaks by averaging), isn't it? May be better to get a value every 60 seconds from cpmCPUTotal1minRev counter? It can show a possible higher values.
Or i'm wrong?

**Comment by v-zhuravlev** [comment]
Hi, 

> The cpmCPUTotal5minRev MIB object provides a more accurate view of the performance of the router over time than the MIB objects cpmCPUTotal1minRev and cpmCPUTotal5secRev . These MIB objects are not accurate because they look at CPU at one minute and five second intervals, respectively. These MIBs enable you to monitor the trends and plan the capacity of your network. The recommended baseline rising threshold for cpmCPUTotal5minRev is 90 percent. Depending on the platform, some routers that run at 90 percent, for example, 2500s, can exhibit performance degradation versus a high-end router, for example, the 7500 series, which can operate fine.

https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15215-collect-cpu-util-snmp.html

Hi, I think that 5mins averages are good here, since you probably should only take action if CPU usage is high for a long period of time. But let's change poll period to 5m in Zabbix template by default to be more consistent.

**Comment by igloo777** [comment]
Hi, I am afraid that with a 5 minute polling period we may lose a short-time spikes. 

Example: let's say that for the 4 minutes we had 100% CPU usage and 1 minute - 20%, the 5min avg will be 84%, but the BGP session with default hold timer 180s may flap at that period. And we will have no action in this case. 

It was just an example (yes, we could monitor the BGP session state additionally). And may be i'm wrong how the cpmCPUTotal5minRev counter works. May be there are averages of max CPU load..

**Comment by v-zhuravlev** [comment]
I agree, but 5m avg metric is recommended by Cisco here for capacity planning and feels enough for that. I can change to 1m if you feel that collecting those spikes are important, probably a bit higher load to the devices but probably still sustainable.

> May be there are averages of max CPU load..

It doesn't say so anywhere, so probably just average.
