### ISSUE TITLE
Zabbix|template for netgear

### ISSUE THREAD

**Issue by Micky-ragazzo** [v-zhuravlev/zbx_template_pack#7]
Hey, i was trying to convert your [template ]( https://github.com/v-zhuravlev/zbx_template_pack/blob/master/in/template_net_netgear.xml) to v3.2 zabbix and without success , so can you tell me  which version it is? how easily convert to 3.2 ? thank you in advance

**Comment by v-zhuravlev** [comment]
As of now, there is 3.2 version available in this project. No need to convert. see other directory in it.

**Comment by v-zhuravlev** [comment]
https://github.com/v-zhuravlev/zbx_template_pack/tree/master/out/net/3.2

**Comment by Micky-ragazzo** [comment]
Thank you so much, it works, but cpu oid  `10.176.1.24 1.3.6.1.4.1.4526.10.1.1.5.1.0 No Such Object available on this agent at this OID` is there any mib file  that support mentioned above oid?

**Comment by v-zhuravlev** [comment]
@Micky-ragazzo , it might be that your netgear doesn't support this OID. Do you have other things in the template working?

**Comment by Micky-ragazzo** [comment]
So, Device contact details | Device description | Device location | History|Device name|Hardware model name | Hardware serial number |  works.  And i found [useful oids for cpu here](https://community.netgear.com/t5/Managed-Switches/M4300-CPU-OID/td-p/1545381) simply exchange for new one and still no result gettting `No Such Instance currently exists at this OID.` do you have any idea? 
![1](https://user-images.githubusercontent.com/8144746/43990474-64814cc6-9d5c-11e8-9c01-154b785ad7a0.png)
![2](https://user-images.githubusercontent.com/8144746/43990475-649a1602-9d5c-11e8-8183-196335a379ed.png)

**Comment by Micky-ragazzo** [comment]
i fix it, forget to add NETGEAR-SWITCHING-MIB, thank you for your help

**Comment by colttt** [comment]
@Micky-ragazzo are you sure? the template use the OID instead of the name, so you don't need the MIB.
